name: Run Tests on Push to Test Branch

on:
  push:
    branches:
      - test

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3 

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'  

      - name: Run Tests with Maven
        run:  pwd  
